In [1]:
import pandas as pd
import numpy as np
import nltk
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

In [2]:
#pip install gensim

In [3]:
data = pd.read_csv('data.csv')

In [4]:
data.head()

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
0,BMW,1 Series M,2011,premium unleaded (required),335.0,6.0,MANUAL,rear wheel drive,2.0,"Factory Tuner,Luxury,High-Performance",Compact,Coupe,26,19,3916,46135
1,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Convertible,28,19,3916,40650
2,BMW,1 Series,2011,premium unleaded (required),300.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,High-Performance",Compact,Coupe,28,20,3916,36350
3,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,"Luxury,Performance",Compact,Coupe,28,18,3916,29450
4,BMW,1 Series,2011,premium unleaded (required),230.0,6.0,MANUAL,rear wheel drive,2.0,Luxury,Compact,Convertible,28,18,3916,34500

In [5]:
data.describe(include='all')

,Make,Model,Year,Engine Fuel Type,Engine HP,Engine Cylinders,Transmission Type,Driven_Wheels,Number of Doors,Market Category,Vehicle Size,Vehicle Style,highway MPG,city mpg,Popularity,MSRP
count,11914,11914,11914.000000,11911,11845.00000,11884.000000,11914,11914,11908.000000,8172,11914,11914,11914.000000,11914.000000,11914.000000,1.191400e+04
unique,48,915,NaN,10,NaN,NaN,5,4,NaN,71,3,16,NaN,NaN,NaN,NaN
top,Chevrolet,Silverado 1500,NaN,regular unleaded,NaN,NaN,AUTOMATIC,front wheel drive,NaN,Crossover,Compact,Sedan,NaN,NaN,NaN,NaN
freq,1123,156,NaN,7172,NaN,NaN,8266,4787,NaN,1110,4764,3048,NaN,NaN,NaN,NaN
mean,NaN,NaN,2010.384338,NaN,249.38607,5.628829,NaN,NaN,3.436093,NaN,NaN,NaN,26.637485,19.733255,1554.911197,4.059474e+04
std,NaN,NaN,7.579740,NaN,109.19187,1.780559,NaN,NaN,0.881315,NaN,NaN,NaN,8.863001,8.987798,1441.855347,6.010910e+04
min,NaN,NaN,1990.000000,NaN,55.00000,0.000000,NaN,NaN,2.000000,NaN,NaN,NaN,12.000000,7.000000,2.000000,2.000000e+03
25%,NaN,NaN,2007.000000,NaN,170.00000,4.000000,NaN,NaN,2.000000,NaN,NaN,NaN,22.000000,16.000000,549.000000,2.100000e+04
50%,NaN,NaN,2015.000000,NaN,227.00000,6.000000,NaN,NaN,4.000000,NaN,NaN,NaN,26.000000,18.000000,1385.000000,2.999500e+04
75%,NaN,NaN,2016.000000,NaN,300.00000,6.000000,NaN,NaN,4.000000,NaN,NaN,NaN,30.000000,22.000000,2009.000000,4.223125e+04
max,NaN,NaN,2017.000000,NaN,1001.00000,16.000000,NaN,NaN,4.000000,NaN,NaN,NaN,354.000000,137.000000,5657.000000,2.065902e+06

In [6]:
#Removing the NAN Values
data.dropna(inplace=True)
data.reset_index(inplace=True)
data.isnull().sum()

index                0
Make                 0
Model                0
Year                 0
Engine Fuel Type     0
Engine HP            0
Engine Cylinders     0
Transmission Type    0
Driven_Wheels        0
Number of Doors      0
Market Category      0
Vehicle Size         0
Vehicle Style        0
highway MPG          0
city mpg             0
Popularity           0
MSRP                 0
dtype: int64

In [7]:
stop_words = set(stopwords.words('english'))
def preprocess(text):
    tokens = word_tokenize(text.lower())
    tokens = [token for token in tokens if token.isalpha() and token not in stop_words]
    return tokens
data['Market Category'] = data['Market Category'].apply(preprocess)
data['Market Category']

0             [factory, tuner, luxury]
1                [luxury, performance]
2                             [luxury]
3                [luxury, performance]
4                             [luxury]
                     ...
8079    [crossover, hatchback, luxury]
8080    [crossover, hatchback, luxury]
8081    [crossover, hatchback, luxury]
8082    [crossover, hatchback, luxury]
8083                          [luxury]
Name: Market Category, Length: 8084, dtype: object

In [8]:
#Perform the bag-of-words approach using CountVectorizer
count_vectorizer = CountVectorizer(tokenizer=lambda doc: doc, lowercase=False)
bow = count_vectorizer.fit_transform(data['Market Category'])
print(bow.toarray()[:5, :10])

[[0 0 0 1 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 1 1]
 [0 0 0 0 0 0 0 0 1 0]]

C:\Users\HP\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\feature_extraction\text.py:528: UserWarning: The parameter 'token_pattern' will not be used since 'tokenizer' is not None'
  warnings.warn(

In [9]:
normalized_count = bow.copy()
for i, j in zip(*normalized_count.nonzero()):
    normalized_count[i, j] = normalized_count[i, j] / len(data['Market Category'][i])
print(normalized_count.toarray()[:5, :10]) # Print the first 5 rows and 10 columns of the matrix

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 1 0]]

In [10]:
#TF-IDF to calculate the importance of each word in the document
tfidf_vectorizer = TfidfVectorizer(tokenizer=lambda doc: doc, lowercase=False)
tfidf = tfidf_vectorizer.fit_transform(data['Market Category'])
print(tfidf.toarray()[:5, :10]) # Print the first 5 rows and 10 columns of the matrix

[[0.         0.         0.         0.6616931  0.         0.
  0.         0.         0.35259679 0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.62784336 0.77833972]
 [0.         0.         0.         0.         0.         0.
  0.         0.         1.         0.        ]
 [0.         0.         0.         0.         0.         0.
  0.         0.         0.62784336 0.77833972]
 [0.         0.         0.         0.         0.         0.
  0.         0.         1.         0.        ]]

In [11]:
#Creating word embeddings using Word2Vec
model = Word2Vec(data['Market Category'], min_count=1)
embeddings = np.zeros((len(data), 100))
for i, tokens in enumerate(data['Market Category']):
    for token in tokens:
        embeddings[i] += model.wv[token]
    embeddings[i] /= len(tokens)

C:\Users\HP\AppData\Local\Temp\ipykernel_42068\2917079914.py:7: RuntimeWarning: invalid value encountered in divide
  embeddings[i] /= len(tokens)

In [12]:
embeddings

array([[-0.01081371,  0.0057243 ,  0.01559494, ..., -0.0384125 ,
         0.01002598,  0.00391788],
       [-0.01936158,  0.00981448,  0.01494137, ..., -0.03419592,
         0.00383476,  0.00652751],
       [-0.01813624,  0.00967213,  0.01674225, ..., -0.04211244,
         0.01080765,  0.00754971],
       ...,
       [-0.01264001,  0.00697713,  0.00522356, ..., -0.02376176,
         0.00932123, -0.00194311],
       [-0.01264001,  0.00697713,  0.00522356, ..., -0.02376176,
         0.00932123, -0.00194311],
       [-0.01813624,  0.00967213,  0.01674225, ..., -0.04211244,
         0.01080765,  0.00754971]])

In [23]:
pip install pandas scikit-learn gensim

Requirement already satisfied: pandas in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (1.5.3)
Requirement already satisfied: scikit-learn in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (1.2.2)
Requirement already satisfied: gensim in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (4.3.2)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (2022.7.1)
Requirement already satisfied: numpy>=1.21.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from pandas) (1.24.2)
Requirement already satisfied: scipy>=1.3.2 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.10.1)
Requirement already satisfied: joblib>=1.1.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.2.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.1.0)
Requirement already satisfied: smart-open>=1.8.1 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from gensim) (7.0.4)
Requirement already satisfied: six>=1.5 in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)
Requirement already satisfied: wrapt in c:\users\hp\appdata\local\programs\python\python310\lib\site-packages (from smart-open>=1.8.1->gensim) (1.14.1)
Note: you may need to restart the kernel to use updated packages.

In [24]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer
from gensim.models import Word2Vec

In [25]:
# Load the dataset
data = pd.read_csv('data.csv')

In [26]:
# Take a look at the dataset
print(data.head())

  Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0
1  BMW    1 Series  2011  premium unleaded (required)      300.0
2  BMW    1 Series  2011  premium unleaded (required)      300.0
3  BMW    1 Series  2011  premium unleaded (required)      230.0
4  BMW    1 Series  2011  premium unleaded (required)      230.0

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0
1               6.0            MANUAL  rear wheel drive              2.0
2               6.0            MANUAL  rear wheel drive              2.0
3               6.0            MANUAL  rear wheel drive              2.0
4               6.0            MANUAL  rear wheel drive              2.0

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe
1                     Luxury,Performance      Compact   Convertible
2                Luxury,High-Performance      Compact         Coupe
3                     Luxury,Performance      Compact         Coupe
4                                 Luxury      Compact   Convertible

   highway MPG  city mpg  Popularity   MSRP
0           26        19        3916  46135
1           28        19        3916  40650
2           28        20        3916  36350
3           28        18        3916  29450
4           28        18        3916  34500

In [27]:
# Bag-of-Words
# Count occurrence
count_vectorizer = CountVectorizer()
bow_matrix = count_vectorizer.fit_transform(data['Model'])
bow_feature_names = count_vectorizer.get_feature_names_out()
print("\nBag-of-Words (Count occurrence):")
print(bow_matrix.toarray())
print("Feature names:", bow_feature_names)

Bag-of-Words (Count occurrence):
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 1 0]
 [0 0 0 ... 0 0 1]]
Feature names: ['10' '100' '124' '12c' '15' '150' '1500' '1500hd' '16' '190' '200' '200h'
 '200sx' '200t' '240' '240sx' '250' '2500' '250h' '2x' '300' '3000gt'
 '300h' '300m' '300zx' '323' '330' '350' '350z' '360' '370z' '400' '400h'
 '420' '430' '450' '450h' '456m' '458' '460' '470' '4c' '4runner' '4x'
 '50' '500' '500e' '500l' '500x' '550' '560' '57' '570' '570s' '575m'
 '599' '600' '6000' '600h' '612' '62' '626' '650s' '718' '740' '760' '780'
 '7x' '80' '850' '86' '90' '900' '9000' '911' '928' '929' '940' '944'
 '960' '968' 'a3' 'a4' 'a5' 'a6' 'a7' 'a8' 'acadia' 'accent' 'acclaim'
 'accord' 'achieva' 'activehybrid' 'aerio' 'aerostar' 'alero' 'allante'
 'allroad' 'alltrack' 'alpina' 'altima' 'am' 'amanti' 'amg' 'and' 'armada'
 'arnage' 'aspen' 'aspire' 'astro' 'ats' 'aurora' 'avalanche' 'avalon'
 'avenger' 'aventador' 'avenue' 'aveo' 'aviator' 'axxess' 'azera' 'aztek'
 'azure' 'b6' 'b7' 'b9' 'baja' 'baron' 'beetle' 'beretta' 'berlinetta'
 'black' 'blackwood' 'blazer' 'bolt' 'bonneville' 'borrego' 'boxster'
 'bravada' 'breeze' 'bronco' 'brooklands' 'brougham' 'brz' 'c3' 'c30'
 'c36' 'c43' 'c70' 'c8' 'cabrio' 'cabriolet' 'cadenza' 'calais' 'caliber'
 'california' 'camaro' 'camry' 'canyon' 'caprice' 'captiva' 'car'
 'caravan' 'cargo' 'carlo' 'carrera' 'cascada' 'catera' 'cavalier'
 'cayenne' 'cayman' 'cc' 'celebrity' 'celica' 'century' 'challenger'
 'charger' 'chevy' 'ciera' 'cirrus' 'city' 'civic' 'cl' 'cla' 'class'
 'classic' 'clk' 'cls' 'cobalt' 'cobra' 'colorado' 'colt' 'concorde'
 'connect' 'continental' 'contour' 'convertible' 'corniche' 'corolla'
 'corrado' 'corsica' 'corvette' 'country' 'coupe' 'cr' 'cressida' 'cross'
 'crosscabriolet' 'crossfire' 'crosstour' 'crosstrek' 'crown' 'cruiser'
 'cruze' 'crx' 'ct' 'ct6' 'cts' 'cube' 'custom' 'cutlass' 'cx' 'dakota'
 'dart' 'dawn' 'daytona' 'db7' 'db9' 'dbs' 'defender' 'del' 'denali'
 'deville' 'diablo' 'diamante' 'diamond' 'discovery' 'drive' 'drophead'
 'dts' 'durango' 'dynasty' 'e55' 'echo' 'eclipse' 'edge' 'edition' 'eight'
 'eighty' 'elantra' 'eldorado' 'electra' 'electric' 'element' 'elise'
 'enclave' 'encore' 'endeavor' 'entourage' 'envision' 'envoy' 'enzo' 'eos'
 'equator' 'equinox' 'equus' 'es' 'escalade' 'escape' 'escort' 'esprit'
 'estate' 'esteem' 'esv' 'eurovan' 'ev' 'evolution' 'evoque' 'evora' 'ex'
 'ex35' 'excel' 'exige' 'expedition' 'explorer' 'expo' 'express' 'ext'
 'f12' 'f430' 'fe' 'festiva' 'ff' 'fiesta' 'final' 'firebird' 'fit' 'five'
 'fj' 'fleetwood' 'flex' 'flying' 'focus' 'forenza' 'forester' 'forte'
 'fox' 'fr' 'freelander' 'freestar' 'freestyle' 'frontier' 'fusion' 'fx'
 'fx35' 'fx45' 'fx50' 'g20' 'g3' 'g35' 'g37' 'g4' 'g5' 'g6' 'g8' 'g80'
 'galant' 'gallardo' 'genesis' 'ghibli' 'ghost' 'gl' 'gla' 'glc' 'gle'
 'gli' 'glk' 'gls' 'golf' 'gran' 'grand' 'gransport' 'granturismo'
 'griffin' 'gs' 'gt' 'gt3' 'gt350' 'gt500' 'gtc' 'gti' 'gto' 'gts' 'gx'
 'h3' 'h3t' 'heritage' 'hhr' 'highlander' 'horizon' 'hr' 'hs' 'hundred'
 'huracan' 'hybrid' 'i3' 'i30' 'i35' 'ia' 'ii' 'ilx' 'im' 'impala'
 'imperial' 'impreza' 'in' 'insight' 'integra' 'intrepid' 'intrigue' 'iq'
 'is' 'isr' 'italia' 'j30' 'jetta' 'jimmy' 'journey' 'juke' 'justy' 'jx'
 'k900' 'kizashi' 'lacrosse' 'lancer' 'land' 'landaulet' 'laser' 'le'
 'leaf' 'legacy' 'legend' 'lesabre' 'levante' 'lfa' 'lhs' 'lightning'
 'limited' 'loyale' 'lr2' 'lr3' 'lr4' 'ls' 'lss' 'lt' 'ltd' 'lucerne'
 'lumina' 'lx' 'm2' 'm3' 'm30' 'm35' 'm37' 'm4' 'm45' 'm5' 'm56' 'm6'
 'macan' 'magnum' 'malibu' 'mans' 'mark' 'matrix' 'max' 'maxima' 'maxx'
 'maybach' 'mazdaspeed' 'mclaren' 'mdx' 'metris' 'metro' 'miata' 'miev'
 'mighty' 'millenia' 'minivan' 'mirage' 'mkc' 'mks' 'mkt' 'mkx' 'mkz'
 'ml55' 'model' 'monaco' 'montana' 'monte' 'montero' 'mp4' 'mpv' 'mr2'
 'mulsanne' 'murano' 'murcielago' 'mustang' 'mx' 'navajo' 'navigator'
 'neon' 'new' 'ninety' 'nitro' 'note' 'nsx' 'nv200' 'nx' 'odyssey' 'omni'
 'optima' 'outback' 'outlander' 'pacifica' 'panamera' 'park' 'paseo'
 'passat' 'passport' 'pathfinder' 'phaeton' 'phantom' 'pickup' 'pilot'
 'plug' 'precis' 'prelude' 'previa' 'prime' 'prius' 'prix' 'prizm' 'probe'
 'protege' 'protege5' 'prowler' 'pt' 'pulsar' 'q3' 'q40' 'q45' 'q5' 'q50'
 'q60' 'q7' 'q70' 'quattro' 'quattroporte' 'quest' 'qx' 'qx4' 'qx50'
 'qx56' 'qx60' 'qx70' 'qx80' 'r32' 'r8' 'rabbit' 'raider' 'rainier'
 'rally' 'ram' 'ramcharger' 'range' 'ranger' 'rapide' 'rav4' 'rc' 'rdx'
 'reatta' 'regal' 'regency' 'rendezvous' 'reno' 'reventon' 'ridgeline'
 'rio' 'riviera' 'rl' 'rlx' 'roadmaster' 'rogue' 'rondo' 'routan' 'rover'
 'royale' 'rs' 'rsx' 'rx' 's2000' 's3' 's4' 's40' 's5' 's6' 's60' 's7'
 's70' 's8' 's80' 's90' 'safari' 'samurai' 'santa' 'savana' 'sc'
 'scaglietti' 'scoupe' 'sebring' 'sedan' 'sedona' 'select' 'sentra'
 'sephia' 'sequoia' 'seraph' 'series' 'seville' 'shadow' 'shelby'
 'sidekick' 'sienna' 'sierra' 'sigma' 'silhouette' 'silver' 'silverado'
 'sixty' 'skylark' 'sl' 'slc' 'slk' 'slr' 'sls' 'slx' 'sol' 'solara'
 'solstice' 'sonata' 'sonic' 'sonoma' 'sorento' 'soul' 'spark' 'special'
 'spectra' 'speed' 'spider' 'spirit' 'sport' 'sportage' 'sportback'
 'sportvan' 'sportwagen' 'spur' 'spyder' 'sq5' 'srt' 'srx' 'ss' 'ssr' 'st'
 'stanza' 'stealth' 'stingray' 'stratus' 'sts' 'suburban' 'sunbird'
 'sundance' 'sunfire' 'superamerica' 'supersports' 'supra' 'supreme' 'sv6'
 'svt' 'svx' 'swift' 'sx4' 'syclone' 't100' 'tacoma' 'tahoe' 'taurus' 'tc'
 'tempo' 'tercel' 'terrain' 'terraza' 'thunderbird' 'tiburon' 'tiguan'
 'titan' 'tl' 'tlx' 'toronado' 'torrent' 'touareg' 'touring' 'town' 'trac'
 'tracker' 'trailblazer' 'trans' 'transit' 'traverse' 'trax' 'tribeca'
 'tribute' 'truck' 'tsx' 'tt' 'tts' 'tucson' 'tundra' 'turismo' 'typhoon'
 'uplander' 'v12' 'v40' 'v50' 'v60' 'v70' 'v8' 'v90' 'van' 'vanagon'
 'vandura' 'vanquish' 'vantage' 'vanwagon' 'veloster' 'venture' 'venza'
 'veracruz' 'verano' 'verona' 'versa' 'veyron' 'vibe' 'victoria' 'vigor'
 'vii' 'viii' 'viper' 'virage' 'vitara' 'voyager' 'wagon' 'ward'
 'windstar' 'wraith' 'wrx' 'x1' 'x3' 'x4' 'x5' 'x6' 'xa' 'xb' 'xc' 'xc60'
 'xc70' 'xc90' 'xd' 'xg300' 'xg350' 'xl' 'xl7' 'xlr' 'xt' 'xt5' 'xterra'
 'xts' 'xuv' 'xv' 'yaris' 'yorker' 'yukon' 'z3' 'z4' 'z71' 'z8' 'zdx'
 'zephyr']

In [29]:
# Normalized count occurrence
bow_matrix_dense = bow_matrix.toarray()
norms = np.linalg.norm(bow_matrix_dense, axis=1)
normalized_bow_matrix = bow_matrix_dense / norms[:, None]

print("\nBag-of-Words (Normalized count occurrence):")
print(normalized_bow_matrix)

Bag-of-Words (Normalized count occurrence):
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]

C:\Users\HP\AppData\Local\Temp\ipykernel_42068\407112027.py:4: RuntimeWarning: invalid value encountered in divide
  normalized_bow_matrix = bow_matrix_dense / norms[:, None]

In [30]:
# TF-IDF
tfidf_vectorizer = TfidfVectorizer()
tfidf_matrix = tfidf_vectorizer.fit_transform(data['Model'])
tfidf_feature_names = tfidf_vectorizer.get_feature_names_out()
print("\nTF-IDF:")
print(tfidf_matrix.toarray())
print("Feature names:", tfidf_feature_names)

TF-IDF:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 1.]]
Feature names: ['10' '100' '124' '12c' '15' '150' '1500' '1500hd' '16' '190' '200' '200h'
 '200sx' '200t' '240' '240sx' '250' '2500' '250h' '2x' '300' '3000gt'
 '300h' '300m' '300zx' '323' '330' '350' '350z' '360' '370z' '400' '400h'
 '420' '430' '450' '450h' '456m' '458' '460' '470' '4c' '4runner' '4x'
 '50' '500' '500e' '500l' '500x' '550' '560' '57' '570' '570s' '575m'
 '599' '600' '6000' '600h' '612' '62' '626' '650s' '718' '740' '760' '780'
 '7x' '80' '850' '86' '90' '900' '9000' '911' '928' '929' '940' '944'
 '960' '968' 'a3' 'a4' 'a5' 'a6' 'a7' 'a8' 'acadia' 'accent' 'acclaim'
 'accord' 'achieva' 'activehybrid' 'aerio' 'aerostar' 'alero' 'allante'
 'allroad' 'alltrack' 'alpina' 'altima' 'am' 'amanti' 'amg' 'and' 'armada'
 'arnage' 'aspen' 'aspire' 'astro' 'ats' 'aurora' 'avalanche' 'avalon'
 'avenger' 'aventador' 'avenue' 'aveo' 'aviator' 'axxess' 'azera' 'aztek'
 'azure' 'b6' 'b7' 'b9' 'baja' 'baron' 'beetle' 'beretta' 'berlinetta'
 'black' 'blackwood' 'blazer' 'bolt' 'bonneville' 'borrego' 'boxster'
 'bravada' 'breeze' 'bronco' 'brooklands' 'brougham' 'brz' 'c3' 'c30'
 'c36' 'c43' 'c70' 'c8' 'cabrio' 'cabriolet' 'cadenza' 'calais' 'caliber'
 'california' 'camaro' 'camry' 'canyon' 'caprice' 'captiva' 'car'
 'caravan' 'cargo' 'carlo' 'carrera' 'cascada' 'catera' 'cavalier'
 'cayenne' 'cayman' 'cc' 'celebrity' 'celica' 'century' 'challenger'
 'charger' 'chevy' 'ciera' 'cirrus' 'city' 'civic' 'cl' 'cla' 'class'
 'classic' 'clk' 'cls' 'cobalt' 'cobra' 'colorado' 'colt' 'concorde'
 'connect' 'continental' 'contour' 'convertible' 'corniche' 'corolla'
 'corrado' 'corsica' 'corvette' 'country' 'coupe' 'cr' 'cressida' 'cross'
 'crosscabriolet' 'crossfire' 'crosstour' 'crosstrek' 'crown' 'cruiser'
 'cruze' 'crx' 'ct' 'ct6' 'cts' 'cube' 'custom' 'cutlass' 'cx' 'dakota'
 'dart' 'dawn' 'daytona' 'db7' 'db9' 'dbs' 'defender' 'del' 'denali'
 'deville' 'diablo' 'diamante' 'diamond' 'discovery' 'drive' 'drophead'
 'dts' 'durango' 'dynasty' 'e55' 'echo' 'eclipse' 'edge' 'edition' 'eight'
 'eighty' 'elantra' 'eldorado' 'electra' 'electric' 'element' 'elise'
 'enclave' 'encore' 'endeavor' 'entourage' 'envision' 'envoy' 'enzo' 'eos'
 'equator' 'equinox' 'equus' 'es' 'escalade' 'escape' 'escort' 'esprit'
 'estate' 'esteem' 'esv' 'eurovan' 'ev' 'evolution' 'evoque' 'evora' 'ex'
 'ex35' 'excel' 'exige' 'expedition' 'explorer' 'expo' 'express' 'ext'
 'f12' 'f430' 'fe' 'festiva' 'ff' 'fiesta' 'final' 'firebird' 'fit' 'five'
 'fj' 'fleetwood' 'flex' 'flying' 'focus' 'forenza' 'forester' 'forte'
 'fox' 'fr' 'freelander' 'freestar' 'freestyle' 'frontier' 'fusion' 'fx'
 'fx35' 'fx45' 'fx50' 'g20' 'g3' 'g35' 'g37' 'g4' 'g5' 'g6' 'g8' 'g80'
 'galant' 'gallardo' 'genesis' 'ghibli' 'ghost' 'gl' 'gla' 'glc' 'gle'
 'gli' 'glk' 'gls' 'golf' 'gran' 'grand' 'gransport' 'granturismo'
 'griffin' 'gs' 'gt' 'gt3' 'gt350' 'gt500' 'gtc' 'gti' 'gto' 'gts' 'gx'
 'h3' 'h3t' 'heritage' 'hhr' 'highlander' 'horizon' 'hr' 'hs' 'hundred'
 'huracan' 'hybrid' 'i3' 'i30' 'i35' 'ia' 'ii' 'ilx' 'im' 'impala'
 'imperial' 'impreza' 'in' 'insight' 'integra' 'intrepid' 'intrigue' 'iq'
 'is' 'isr' 'italia' 'j30' 'jetta' 'jimmy' 'journey' 'juke' 'justy' 'jx'
 'k900' 'kizashi' 'lacrosse' 'lancer' 'land' 'landaulet' 'laser' 'le'
 'leaf' 'legacy' 'legend' 'lesabre' 'levante' 'lfa' 'lhs' 'lightning'
 'limited' 'loyale' 'lr2' 'lr3' 'lr4' 'ls' 'lss' 'lt' 'ltd' 'lucerne'
 'lumina' 'lx' 'm2' 'm3' 'm30' 'm35' 'm37' 'm4' 'm45' 'm5' 'm56' 'm6'
 'macan' 'magnum' 'malibu' 'mans' 'mark' 'matrix' 'max' 'maxima' 'maxx'
 'maybach' 'mazdaspeed' 'mclaren' 'mdx' 'metris' 'metro' 'miata' 'miev'
 'mighty' 'millenia' 'minivan' 'mirage' 'mkc' 'mks' 'mkt' 'mkx' 'mkz'
 'ml55' 'model' 'monaco' 'montana' 'monte' 'montero' 'mp4' 'mpv' 'mr2'
 'mulsanne' 'murano' 'murcielago' 'mustang' 'mx' 'navajo' 'navigator'
 'neon' 'new' 'ninety' 'nitro' 'note' 'nsx' 'nv200' 'nx' 'odyssey' 'omni'
 'optima' 'outback' 'outlander' 'pacifica' 'panamera' 'park' 'paseo'
 'passat' 'passport' 'pathfinder' 'phaeton' 'phantom' 'pickup' 'pilot'
 'plug' 'precis' 'prelude' 'previa' 'prime' 'prius' 'prix' 'prizm' 'probe'
 'protege' 'protege5' 'prowler' 'pt' 'pulsar' 'q3' 'q40' 'q45' 'q5' 'q50'
 'q60' 'q7' 'q70' 'quattro' 'quattroporte' 'quest' 'qx' 'qx4' 'qx50'
 'qx56' 'qx60' 'qx70' 'qx80' 'r32' 'r8' 'rabbit' 'raider' 'rainier'
 'rally' 'ram' 'ramcharger' 'range' 'ranger' 'rapide' 'rav4' 'rc' 'rdx'
 'reatta' 'regal' 'regency' 'rendezvous' 'reno' 'reventon' 'ridgeline'
 'rio' 'riviera' 'rl' 'rlx' 'roadmaster' 'rogue' 'rondo' 'routan' 'rover'
 'royale' 'rs' 'rsx' 'rx' 's2000' 's3' 's4' 's40' 's5' 's6' 's60' 's7'
 's70' 's8' 's80' 's90' 'safari' 'samurai' 'santa' 'savana' 'sc'
 'scaglietti' 'scoupe' 'sebring' 'sedan' 'sedona' 'select' 'sentra'
 'sephia' 'sequoia' 'seraph' 'series' 'seville' 'shadow' 'shelby'
 'sidekick' 'sienna' 'sierra' 'sigma' 'silhouette' 'silver' 'silverado'
 'sixty' 'skylark' 'sl' 'slc' 'slk' 'slr' 'sls' 'slx' 'sol' 'solara'
 'solstice' 'sonata' 'sonic' 'sonoma' 'sorento' 'soul' 'spark' 'special'
 'spectra' 'speed' 'spider' 'spirit' 'sport' 'sportage' 'sportback'
 'sportvan' 'sportwagen' 'spur' 'spyder' 'sq5' 'srt' 'srx' 'ss' 'ssr' 'st'
 'stanza' 'stealth' 'stingray' 'stratus' 'sts' 'suburban' 'sunbird'
 'sundance' 'sunfire' 'superamerica' 'supersports' 'supra' 'supreme' 'sv6'
 'svt' 'svx' 'swift' 'sx4' 'syclone' 't100' 'tacoma' 'tahoe' 'taurus' 'tc'
 'tempo' 'tercel' 'terrain' 'terraza' 'thunderbird' 'tiburon' 'tiguan'
 'titan' 'tl' 'tlx' 'toronado' 'torrent' 'touareg' 'touring' 'town' 'trac'
 'tracker' 'trailblazer' 'trans' 'transit' 'traverse' 'trax' 'tribeca'
 'tribute' 'truck' 'tsx' 'tt' 'tts' 'tucson' 'tundra' 'turismo' 'typhoon'
 'uplander' 'v12' 'v40' 'v50' 'v60' 'v70' 'v8' 'v90' 'van' 'vanagon'
 'vandura' 'vanquish' 'vantage' 'vanwagon' 'veloster' 'venture' 'venza'
 'veracruz' 'verano' 'verona' 'versa' 'veyron' 'vibe' 'victoria' 'vigor'
 'vii' 'viii' 'viper' 'virage' 'vitara' 'voyager' 'wagon' 'ward'
 'windstar' 'wraith' 'wrx' 'x1' 'x3' 'x4' 'x5' 'x6' 'xa' 'xb' 'xc' 'xc60'
 'xc70' 'xc90' 'xd' 'xg300' 'xg350' 'xl' 'xl7' 'xlr' 'xt' 'xt5' 'xterra'
 'xts' 'xuv' 'xv' 'yaris' 'yorker' 'yukon' 'z3' 'z4' 'z71' 'z8' 'zdx'
 'zephyr']

In [31]:
# Word2Vec
# Tokenize the data
tokenized_data = [model.split() for model in data['Model']]

In [32]:
# Train Word2Vec model
word2vec_model = Word2Vec(sentences=tokenized_data, vector_size=100, window=5, min_count=1, workers=4)

In [33]:
# Get Word2Vec embeddings
word2vec_embeddings = [np.mean([word2vec_model.wv[token] for token in model], axis=0) for model in tokenized_data]
print("\nWord2Vec Embeddings:")
print(np.array(word2vec_embeddings))

Word2Vec Embeddings:
[[-0.00685435  0.0011278   0.00170766 ... -0.00022534 -0.00811109
  -0.00051412]
 [-0.00623394  0.00365357  0.00103452 ... -0.0020861  -0.01083789
   0.00341242]
 [-0.00623394  0.00365357  0.00103452 ... -0.0020861  -0.01083789
   0.00341242]
 ...
 [-0.00059128 -0.00600316 -0.00509228 ... -0.00755747 -0.00340728
  -0.00695989]
 [-0.00059128 -0.00600316 -0.00509228 ... -0.00755747 -0.00340728
  -0.00695989]
 [-0.00980532  0.00137023 -0.00658715 ... -0.00082586 -0.00216137
   0.00255175]]